In [ ]:
import pandas as pd

dados_treino = pd.read_csv('https://caelum-online-public.s3.amazonaws.com/1638-word-embedding/treino.csv')
dados_teste = pd.read_csv('https://caelum-online-public.s3.amazonaws.com/1638-word-embedding/teste.csv')



In [ ]:
dados_treino.head()

title  \
0  Após polêmica, Marine Le Pen diz que abomina n...   
1  Macron e Le Pen vão ao 2º turno na França, em ...   
2  Apesar de larga vitória nas legislativas, Macr...   
3  Governo antecipa balanço, e Alckmin anuncia qu...   
4  Após queda em maio, a atividade econômica sobe...   

                                                text        date   category  \
0  A candidata da direita nacionalista à Presidên...  2017-04-28      mundo   
1  O centrista independente Emmanuel Macron e a d...  2017-04-23      mundo   
2  As eleições legislativas deste domingo (19) na...  2017-06-19      mundo   
3  O número de ocorrências de homicídios dolosos ...  2015-07-24  cotidiano   
4  A economia cresceu 0,25% no segundo trimestre,...  2017-08-17    mercado   

  subcategory                                               link  
0         NaN  http://www1.folha.uol.com.br/mundo/2017/04/187...  
1         NaN  http://www1.folha.uol.com.br/mundo/2017/04/187...  
2         NaN  http://www1.folha.uol.com.br/mundo/2017/06/189...  
3         NaN  http://www1.folha.uol.com.br/cotidiano/2015/07...  
4         NaN  http://www1.folha.uol.com.br/mercado/2017/08/1...

In [ ]:
dados_teste.head()

title  \
0                                     Grandes irmãos   
1  Haddad congela orçamento e suspende emendas de...   
2  Proposta de reforma da Fifa tem a divulgação d...   
3  Mercado incipiente, internet das coisas conect...   
4  Mortes: Psicanalista, estudou o autismo em cri...   

                                                text        date   category  \
0  RIO DE JANEIRO - O Brasil, cada vez menos famí...  2017-03-06    colunas   
1  O prefeito de São Paulo, Fernando Haddad (PT),...  2016-08-10    colunas   
2  A Fifa divulgou, nesta quinta (10), um relatór...  2015-10-09    esporte   
3  Bueiros, coleiras, aparelhos hospitalares, ele...  2016-11-09    mercado   
4  Toda vez que o grupo de amigos de Silvana Rabe...  2017-02-07  cotidiano   

     subcategory                                               link  
0      ruycastro  http://www1.folha.uol.com.br/colunas/ruycastro...  
1  monicabergamo  http://www1.folha.uol.com.br/colunas/monicaber...  
2            NaN  http://www1.folha.uol.com.br/esporte/2015/09/1...  
3            NaN  http://www1.folha.uol.com.br/mercado/2016/09/1...  
4            NaN  http://www1.folha.uol.com.br/cotidiano/2017/07...

In [ ]:
dados_treino.iloc[0].title

'Após polêmica, Marine Le Pen diz que abomina negacionistas do Holocausto'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

texto = [
    "tenha um bom dia",
    "tenha um péssimo dia",
    "tenha um ótimo dia",
    "tenha um dia ruim"
]

vetorizador = CountVectorizer()
vetorizador.fit(texto)

CountVectorizer()

In [ ]:
print(vetorizador.vocabulary_)

{'tenha': 4, 'um': 5, 'bom': 0, 'dia': 1, 'péssimo': 2, 'ótimo': 6, 'ruim': 3}


In [ ]:
vetor_bom = vetorizador.transform(["bom"])

print(vetor_bom.toarray())

[[1 0 0 0 0 0 0]]


In [ ]:
vetor_bom = vetorizador.transform(["ótimo"])

print(vetor_bom.toarray())

[[0 0 0 0 0 0 1]]


Word2vec

In [ ]:
from gensim.models import KeyedVectors

modelo = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/Word2Vec/cbow_s300.txt')

In [ ]:
modelo.most_similar('espanha')

[('frança', 0.7710400819778442),
 ('itália', 0.7417077422142029),
 ('dinamarca', 0.7252728939056396),
 ('grécia', 0.7176815271377563),
 ('inglaterra', 0.7163249254226685),
 ('holanda', 0.7146565914154053),
 ('bélgica', 0.6959753632545471),
 ('es-panha', 0.6957015991210938),
 ('grã-bretanha', 0.6953411102294922),
 ('suécia', 0.6767714023590088)]

In [ ]:
modelo.most_similar(positive=["brasil", "argentina"])

[('chile', 0.6781662702560425),
 ('peru', 0.6348033547401428),
 ('venezuela', 0.6273865103721619),
 ('equador', 0.6037014722824097),
 ('bolívia', 0.6017140746116638),
 ('haiti', 0.5993807315826416),
 ('méxico', 0.5962306261062622),
 ('paraguai', 0.5957703590393066),
 ('uruguai', 0.5903672575950623),
 ('japão', 0.5893509984016418)]

In [ ]:
#nuvens -> nuvem : estrelas -> estrela
#nuvens + estrela - nuvem = estrelas

modelo.most_similar(positive=["nuvens", "estrela"], negative=["nuvem"])

[('estrelas', 0.5497429966926575),
 ('plêiades', 0.379197895526886),
 ('colinas', 0.3746805191040039),
 ('trovoadas', 0.373703271150589),
 ('sombras', 0.3734194040298462),
 ('pombas', 0.3726757764816284),
 ('corredoras', 0.3640727698802948),
 ('cigarras', 0.36065393686294556),
 ('galáxias', 0.35754913091659546),
 ('luas', 0.3575345277786255)]

In [ ]:
modelo.most_similar(positive=["medico", "mulher"], negative=["homem"])

[('enfermeira', 0.5567789673805237),
 ('esposa', 0.540894627571106),
 ('mãe', 0.5147395730018616),
 ('filha', 0.5052310824394226),
 ('namorada', 0.49705660343170166),
 ('filhinha', 0.49672722816467285),
 ('irmã', 0.4958304166793823),
 ('parenta', 0.4849744439125061),
 ('sobrinha', 0.4843062460422516),
 ('babá', 0.48186036944389343)]

In [ ]:
modelo.most_similar(positive=["professor", "mulher"], negative=["homem"])

[('professora', 0.6192208528518677),
 ('aluna', 0.5449554324150085),
 ('esposa', 0.4978231191635132),
 ('ex-aluna', 0.4884248375892639),
 ('namorada', 0.4737858772277832),
 ('enfermeira', 0.4728144109249115),
 ('filha', 0.467373788356781),
 ('irmã', 0.45845913887023926),
 ('ex-namorada', 0.45824766159057617),
 ('ex-professora', 0.4510470926761627)]

# Vetorização de textos

In [ ]:
dados_treino.title.loc[12]

"Daniel Craig será stormtrooper em novo 'Star Wars', diz ator"

In [ ]:
import nltk
nltk.download('punkt')
import string

def tokenizador(texto):
  texto = texto.lower()
  lista_alfanumerico = []

  for token_valido in nltk.word_tokenize(texto):
    if token_valido in string.punctuation: continue
    lista_alfanumerico.append(token_valido)

  return lista_alfanumerico

tokenizador("Texto Exemplo, 1234!")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['texto', 'exemplo', '1234']

In [ ]:
import numpy as np
def combinacao_vetores_por_soma(palavras_numeros):
  vetor_resultante = np.zeros(300)

  for pn in palavras_numeros:
    try:
      vetor_resultante += modelo.get_vector(pn)
    except KeyError:
      if pn.isnumeric():
        pn = "0"*len(pn)
        vetor_resultante += modelo.get_vector(pn)
      else:
        vetor_resultante += modelo.get_vector("unknown")
  return vetor_resultante

In [ ]:
palavras_numeros = tokenizador("Frase Exemplo")
vetor_resultante = combinacao_vetores_por_soma(palavras_numeros)
print(len(vetor_resultante))
print(vetor_resultante)

300
[ 3.44038010e-01  1.03551999e-01  3.17570008e-02  6.34731025e-01
 -1.85134992e-01 -2.38715993e-01  3.59508976e-01  4.32909995e-01
  1.54239982e-02  1.48930103e-02  2.43712999e-01  3.45398001e-01
  2.78683990e-01  1.98045000e-01 -8.50249901e-02  8.22790004e-02
 -5.49331971e-01  6.81780018e-02  2.45528005e-01  4.25998867e-03
 -7.78042972e-01 -4.47360016e-02  2.92254999e-01  2.27771005e-01
 -2.76682004e-01 -4.69911009e-01 -2.59007014e-01 -1.84272999e-01
 -3.80580995e-01 -2.76219994e-02 -3.47883997e-01 -2.00868002e-01
 -3.48509960e-02 -1.94766002e-01 -3.44370045e-02  7.82510005e-02
  1.08333997e-01  4.40776005e-01  2.93099880e-03 -3.47897008e-01
 -1.93056008e-01  7.75275022e-01  3.41959998e-01  3.41940010e-01
 -3.76720000e-02  6.53095990e-01  2.06599006e-01  1.27740998e-01
 -7.59760011e-02 -1.07328996e-01 -2.74974003e-01 -3.20950039e-02
  3.74537991e-01 -3.37490030e-02  5.57010025e-02 -7.78579991e-02
  1.82776999e-01  9.75370035e-02 -6.39137000e-01  2.35388000e-01
  1.06006999e-01  2.2

In [ ]:
def matriz_vetores(textos):
  x = len(textos)
  y = 300
  matriz = np.zeros((x,y))

  for i in range(x):
    palavras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_vetores_por_soma(palavras_numeros)

  return matriz


matriz_vetores_treino = matriz_vetores(dados_treino.title)
matriz_vetores_teste = matriz_vetores(dados_teste.title)

print(matriz_vetores_treino.shape)
print(matriz_vetores_teste.shape)

(90000, 300)
(20513, 300)


In [ ]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(max_iter = 200)

LR.fit(matriz_vetores_treino, dados_treino.category)

LogisticRegression(max_iter=200)

In [ ]:
LR.score(matriz_vetores_teste, dados_teste.category)

0.7957880368546775

In [ ]:
label_prevista = LR.predict(matriz_vetores_teste)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(dados_teste.category,label_prevista))

              precision    recall  f1-score   support

     colunas       0.86      0.71      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.92      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513



In [ ]:
from sklearn.dummy import DummyClassifier

DC = DummyClassifier(strategy='stratified')

DC.fit(matriz_vetores_treino, dados_treino.category)

label_prevista_dc = DC.predict(matriz_vetores_teste)
print(classification_report(dados_teste.category, label_prevista_dc))

              precision    recall  f1-score   support

     colunas       0.29      0.16      0.21      6103
   cotidiano       0.09      0.18      0.12      1698
     esporte       0.23      0.17      0.19      4663
   ilustrada       0.01      0.21      0.02       131
     mercado       0.29      0.17      0.21      5867
       mundo       0.11      0.18      0.14      2051

    accuracy                           0.17     20513
   macro avg       0.17      0.18      0.15     20513
weighted avg       0.24      0.17      0.19     20513



In [ ]:
LRM = LogisticRegression(max_iter=150, multi_class='multinomial')

LRM.fit(matriz_vetores_treino, dados_treino.category)

label_prevista_lrm = LRM.predict(matriz_vetores_teste)
print(classification_report(dados_teste.category, label_prevista_lrm))

              precision    recall  f1-score   support

     colunas       0.86      0.71      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.92      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513



In [ ]:
prob_prevista_lrm = LRM.predict_proba(matriz_vetores_teste)

In [ ]:
prob_prevista_lrm[0]

array([0.91551372, 0.0210651 , 0.00483641, 0.0213543 , 0.02786393,
       0.00936653])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier()
RFC.fit(matriz_vetores_treino, dados_treino.category)
label_prevista_rfc = RFC.predict(matriz_vetores_teste)
print(classification_report(dados_teste.category, label_prevista_rfc))

              precision    recall  f1-score   support

     colunas       0.90      0.63      0.74      6103
   cotidiano       0.53      0.73      0.61      1698
     esporte       0.91      0.78      0.84      4663
   ilustrada       0.09      0.87      0.16       131
     mercado       0.77      0.78      0.78      5867
       mundo       0.61      0.80      0.69      2051

    accuracy                           0.73     20513
   macro avg       0.63      0.76      0.64     20513
weighted avg       0.80      0.73      0.75     20513



SKIP-GRAM

In [ ]:
modelo_SKIP = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/Word2Vec/skip_s300.txt')

In [ ]:
def combinacao_vetores_por_soma_skip(palavras_numeros):
  vetor_resultante = np.zeros(300)

  for pn in palavras_numeros:
    try:
      vetor_resultante += modelo_SKIP.get_vector(pn)
    except KeyError:
      if pn.isnumeric():
        pn = "0"*len(pn)
        vetor_resultante += modelo_SKIP.get_vector(pn)
      else:
        vetor_resultante += modelo_SKIP.get_vector("unknown")
  return vetor_resultante

In [ ]:
def matriz_vetores_skip(textos):
  x = len(textos)
  y = 300
  matriz = np.zeros((x,y))

  for i in range(x):
    palavras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_vetores_por_soma_skip(palavras_numeros)

  return matriz


In [ ]:
matriz_vetores_treino_skip = matriz_vetores_skip(dados_treino.title)
matriz_vetores_teste_skip = matriz_vetores_skip(dados_teste.title)

In [ ]:
LR_skip = LogisticRegression(max_iter = 250)

LR_skip.fit(matriz_vetores_treino_skip, dados_treino.category)
label_prevista_skip = LR_skip.predict(matriz_vetores_teste_skip)

print(classification_report(dados_teste.category, label_prevista_skip))

              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.63      0.81      0.70      1698
     esporte       0.93      0.89      0.91      4663
   ilustrada       0.15      0.91      0.26       131
     mercado       0.84      0.81      0.83      5867
       mundo       0.76      0.86      0.80      2051

    accuracy                           0.81     20513
   macro avg       0.69      0.83      0.71     20513
weighted avg       0.84      0.81      0.82     20513

